---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gacek-data
  labels:
    name: gacek-data
spec:
  capacity:
    storage: 10Mi
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - vers=4.2
  nfs:
    path: /srv/gacek
    server: 172.22.13.2
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gacek-data
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: standard
  resources:
    requests:
      storage: 10Mi
  selector:
    matchLabels:
      name: gacek-data
